from .genetic_algorithm import NQueensGeneticAlgorithm
from .backtracking import NQueensBacktracking
from .hill_climbing import NQueensHillClimbing
from .simulated_annealing import NQueensSimulatedAnnealing